FIT5120-TA02/NutriPeek-frontend

- src/app/[locale]/ChildInfo/page.tsx
- src/app/[locale]/page.tsx
Converted the page component into an async function as required by Next.js 15.
Fixes type error caused by mismatched params expectations.
Ensures project can build and deploy successfully after Next.js version upgrade.
> Next.js 15 routing requirements

- package-lock.json
- package.json
- src/app/[locale]/ChildInfo/page.tsx
- src/app/[locale]/NutriResult/page.tsx
- src/app/[locale]/NutriScan/page.tsx
- src/app/[locale]/page.tsx
- src/app/[locale]/profile/page.tsx
- src/app/layout.tsx
- src/components/ui/ConfirmDialog.tsx
- src/components/ui/Navbar.tsx
Added the ability for users to delete individual child profiles with confirmation.
Unified the confirmation dialog UI using a new reusable ConfirmDialog component.
Improved the success notifications using sonner toast messages.
Manually tested deleting a single child profile and verified removal from both UI and localStorage.
Verified success toasts appear correctly after actions.
Verified that editing, saving, and canceling edits work without errors.
Verified the confirmation dialog styling across different screen sizes.
-
> add individual card delete feature and unify confirm dialog style

- src/app/[locale]/choosepic/[shortcode]/page.tsx
- Implemented dynamic routing for `choosepic/[shortcode]` page.
- This allows users to access the upload page dynamically based on the QR code they scan.
- Previously the route was static, causing 404 errors when scanning a QR code.
- Locally tested by scanning a generated QR code.
- Confirmed that after scanning, the browser correctly opens `/choosepic/[shortcode]` page.
- Successfully uploaded images and verified that backend receives the upload.
-
> add dynamic route for choosepic/[shortcode] page.

- .env
- src/app/[locale]/NutriResult/page.tsx
- src/app/[locale]/NutriScan/page.tsx
- src/app/[locale]/choosepic/[shortcode]/page.tsx
- Replace hardcoded backend API URLs with `process.env.NEXT_PUBLIC_API_URL`
- Add `.env.local` for API URL management
- Improve flexibility and security
- Support easy switching between development and production environments
Confirm API requests (`generate_upload_qr`, `upload`, `get result`) are working through environment variables.
-
> swap ip to env file

- src/app/[locale]/NutriScan/page.tsx
- src/app/[locale]/upload/[shortcode]/page.tsx
- Refactor upload flow to correctly fetch analysis result after successful image upload.
- Add mobile device detection: mobile users are guided to view results on a computer.
- Manual upload testing on both desktop and mobile devices.
- Verified that uploaded image triggers result analysis.
> handle upload result fetching after upload success

- src/app/[locale]/upload/[shortcode]/page.tsx
> clean UploadPage and fix upload result flow

- package.json
> Resolve merge conflicts and clean package.json

- next.config.js
> Fix redeploy

- src/app/[locale]/NutriScan/page.tsx
> fix: resolve remaining merge conflict markers

- package-lock.json
- src/app/[locale]/Welcome/page.tsx
- src/app/layout.tsx
- src/components/ui/Navbar.tsx
> resolve layout.tsx merge conflict

- src/components/NutriGapChart/RecommendationComparison.tsx
> change import router

- src/components/NutriGapChart/RecommendationComparison.tsx
> change props type to array

- src/components/NutriGapChart/NutrientGapBarChart.tsx
> add miss "t" in router

- src/components/ui/Navbar.tsx
> [Chore] Remove NutriGap from NavBar

- src/app/[locale]/Profile/page.tsx
> [Chore] Force git to recognise capitalised directory

- src/components/BuildPlate/BuildPlateFeature.tsx
- src/components/BuildPlate/FoodGrid.tsx
- src/components/BuildPlate/FoodNutrientTable.tsx
- src/components/BuildPlate/NutrientInfoBanner.tsx
- src/components/BuildPlate/NutritionChart.tsx
- src/components/Welcome/PlateBuilderSection.tsx
- src/components/ui/Banner.tsx
- src/components/ui/InfoPopup.tsx
- src/components/ui/Navbar.tsx
- src/locales/en.json
- src/locales/zh.json
> [Fix] Build plate feedbacks + Disable on mobile

- src/components/MatchAndLearn/DifficultySelector.tsx
- src/components/MatchAndLearn/GameBoard.tsx
- src/components/MatchAndLearn/GameCard.tsx
- src/components/MatchAndLearn/MatchAndLearnGame.tsx
- src/components/MatchAndLearn/PageWrapper.tsx
- src/components/MatchAndLearn/constants.ts
- src/components/MatchAndLearn/types.ts
- src/hooks/useDeviceDetection.ts
- src/hooks/useStorage.ts
- src/locales/en.json
- src/locales/zh.json
Implement mobile-responsive design and difficulty level management
- Added constants for difficulty levels with corresponding card counts for desktop and mobile.
- Enhanced DifficultySelector to dynamically display difficulty descriptions based on device type.
- Updated GameBoard and GameCard components to adjust layouts and styles for mobile devices.
- Introduced useDeviceDetection hook for detecting device type and adapting UI accordingly.
- Refactored MatchAndLearnGame to prepare cards based on device type and difficulty level.
- Improved PageWrapper for responsive title and description display.
- Adding pictures can …
> [Refactor] Match & Learn RWD

- src/app/[locale]/Welcome/page.tsx
- src/components/MatchAndLearn/QuizPopup.tsx
- src/components/Welcome/FooterSection.tsx
- src/components/Welcome/ProductVideoSection.tsx
- src/components/Welcome/index.ts
add product video and fix small viewport issue on quiz popup
> [Feat] Product Video

- src/components/SeasonalFood/FarmersMarketMap.module.css
- src/components/SeasonalFood/LeafletMap.tsx
> [Hotfix] Unpure Selectors on Leaflet Map CSS

- src/app/[locale]/Note/page.tsx
- src/app/[locale]/NutriRecommend/page.tsx
- src/app/[locale]/NutriScan/page.tsx
- src/components/BuildPlate/BuildPlateFeature.tsx
- src/components/NutriGap/ActivityAnalysisView.tsx
- src/components/NutriRecommend/LoadingSpinner.tsx
- src/components/NutriScan/FoodIngredients/IngredientItem.tsx
- src/components/NutriScan/FoodIngredients/IngredientsList.tsx
- src/components/NutriScan/Meal/MealScanCard.tsx
- src/components/NutriScan/ResultsSection.tsx
- src/components/NutriScan/ScanningSection.tsx
- src/components/layouts/PinnedItemsContent.tsx
- src/hooks/useNoteEvents.ts
- src/libs/NoteService.ts
> [Fix] Minor Bugs

- src/app/[locale]/Note/page.tsx
- src/app/[locale]/NutriRecommend/page.tsx
- src/app/[locale]/Welcome/page.tsx
- src/components/SeasonalFood/SeasonalFoodCTA.tsx
- src/components/Welcome/SeasonalFoodSection.tsx
- src/components/Welcome/index.ts
- src/components/ui/SeasonalFoodCTA.tsx
- src/utils/assetHelpers.ts
> [Feat]: Add Seasonal Food CTA accross pages + Add New Seasonal Food Section to Landing Page

- src/app/globals.css
- src/app/legal-policy-test/page.tsx
- src/components/LegalPolicy/LegalPolicies.tsx
- src/components/LegalPolicy/LegalPolicyPopup.tsx
- src/components/LegalPolicy/PolicyContent.tsx
- src/components/LegalPolicy/index.ts
- src/components/Welcome/FooterSection.tsx
> [Feat] Legal Policies

- src/app/[locale]/Note/page.tsx
- src/app/[locale]/NutriGap/page.tsx
- src/app/[locale]/NutriRecommend/page.tsx
- src/app/[locale]/SeasonalFood/page.tsx
- src/app/[locale]/Welcome/page.tsx
- src/app/layout.tsx
- src/components/BuildPlate/PageWrapper.tsx
- src/components/MatchAndLearn/PageWrapper.tsx
- src/components/Welcome/ProductVideoSection.tsx
- src/components/layouts/FloatingEmojisLayout.tsx
> [Fix] Emoji Layout Lag + Don't autoplay video

- sitemap.md
> [Chore] Sitemap

- src/components/SeasonalFood/FarmersMarketMap.tsx
> feat: replace earth emoji with NavigationArrow icon in location selector

- package-lock.json
- package.json
- src/components/Welcome/SeasonalFoodSection.tsx
> feat: replace emoji icons with Phosphor icons in SeasonalFoodSection

- sitemap.md
- src/app/[locale]/page.tsx
- src/app/layout.tsx
- src/components/ui/Navbar.tsx
> Remove password authentication and redirect root to Welcome page
